metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
  - module: docker
    metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_locale:
      format: offset
  - add_host_metadata:
      netinfo.enabled: true

output.elasticsearch:
  hosts: "elasticsearch:9200"

setup.dashboards:
  enabled: true

setup.kibana:
  host: "kibana:5601"

xpack.monitoring:
  enabled: true
  elasticsearch:
